[build]
# Uncomment the relevant target for your chip here (ESP32, ESP32-S2, ESP32-S3 or ESP32-C3)
{% if mcu != "esp32" %}#{% endif %}target = "xtensa-esp32-espidf"
{% if mcu != "esp32s2" %}#{% endif %}target = "xtensa-esp32s2-espidf"
{% if mcu != "esp32s3" %}#{% endif %}target = "xtensa-esp32s3-espidf"
{% if mcu != "esp32c3" %}#{% endif %}target = "riscv32imc-esp-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"

# Future - necessary for the experimental "native build" of esp-idf-sys with ESP32C3
# See also https://github.com/ivmarkov/embuild/issues/16
rustflags = ["-C", "default-linker-libraries"]

[unstable]
{% if std %}
build-std = ["std", "panic_abort"]{% else %}build-std = ["core", "alloc", "panic_abort"]{% endif %}
{% if espidfver != "v4.3.2" %}#{% endif %}build-std-features = ["panic_immediate_abort"] # Required for older ESP-IDF versions without a realpath implementation

[env]
# Note: these variables are not used when using pio builder
# Enables the esp-idf-sys "native" build feature (`cargo build --features native`) to build against ESP-IDF stable (v4.4)
{% if espidfver != "v4.4" %}#{% endif %}ESP_IDF_VERSION = { value = "branch:release/v4.4" }
# Enables the esp-idf-sys "native" build feature (`cargo build --features native`) to build against ESP-IDF master (mainline)
{% if espidfver != "mainline" %}#{% endif %}ESP_IDF_VERSION = { value = "master" }

# use globaly installed esp_idf instead of downloading new for each project
# defaults to ~/.espressif
# comment out this line to use local esp-idf
ESP_IDF_TOOLS_INSTALL_DIR = "global"
# needed for non risk5 builds
PIP_USER = "no"
LIBCLANG_PATH = "/home/jakob/.espressif/tools/xtensa-esp32-elf-clang/esp-13.0.0-20211203-x86_64-unknown-linux-gnu/lib"